import Head from 'next/head';
import Blocks from '../components/home/Blocks';
import Main from '../components/Main';
import Container from '../components/Container';

export default function Home() {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <Blocks />
      </Main>
    </Container>
  );
}
